export const CATEGORY_TO_DOCS_PATH: Record<string, string> = {
  "AI & LLM Integration": "docs/ai--llm-integration.md",
  "Art, Culture & Media": "docs/art-culture--media.md",
  "Browser Automation & Web Scraping": "docs/browser-automation--web-scraping.md",
  "Build & Deployment Tools": "docs/build--deployment-tools.md",
  "Cloud Platforms & Services": "docs/cloud-platforms--services.md",
  "Code Analysis & Quality": "docs/code-analysis--quality.md",
  "Code Execution": "docs/code-execution.md",
  "Communication & Messaging": "docs/communication--messaging.md",
  "Content Management Systems": "docs/content-management-systems-cms.md",
  "Data Analysis & Business Intelligence": "docs/data-analysis--business-intelligence.md",
  Databases: "docs/databases.md",
  "Developer Productivity & Utilities": "docs/developer-productivity--utilities.md",
  Filesystems: "docs/filesystems.md",
  "Finance & Crypto": "docs/finance--crypto.md",
  Frameworks: "docs/frameworks.md",
  Gaming: "docs/gaming.md",
  "Hardware & IoT": "docs/hardware--iot.md",
  "Healthcare & Life Sciences": "docs/healthcare--life-sciences.md",
  Infrastructure: "docs/infrastructure.md",
  "Knowledge Management & Memory": "docs/knowledge-management--memory.md",
  "Location & Maps": "docs/location--maps.md",
  "Marketing, Sales & CRM": "docs/marketing-sales--crm.md",
  "Monitoring & Observability": "docs/monitoring--observability.md",
  "Multimedia Processing": "docs/multimedia-processing.md",
  "Operating System & Command Line": "docs/operating-system--command-line.md",
  "Project & Task Management": "docs/project--task-management.md",
  "Real Estate & Home Services": "docs/real-estate--home-services.md",
  "Science & Research": "docs/science--research.md",
  Search: "docs/search.md",
  Security: "docs/security.md",
  "Social Media & Content Platforms": "docs/social-media--content-platforms.md",
  Sports: "docs/sport.md",
  "Travel & Transportation": "docs/travel--transportation.md",
  "Utilities & Helpers": "docs/utilities--helpers.md",
  "Version Control": "docs/version-control.md",
};
